### ISSUE TITLE
p2p 

### ISSUE THREAD

**Issue by samhavens** [sudomesh/disaster-radio#11]
Has there been consideration of trying to directly connect clients? An in-exhaustive comparison of potential pros and cons:

### Pros

1. Can extend the network. A U-shaped topology could become a disk if enough users were in the middle of the U.
2. Resiliency. One, many, or even all of the DR nodes could be compromised, but users could still share information.
3. Faster map loading. If a user has no maps cached, but has 5 users around them with cached maps, it is possible to parallelize the loading a la torrents. 

### Cons

1. Increased complexity
2. Potential battery drain

#### Implementations

The peer-to-peer communication could be implemented via one or more of:

* Bluetooth
* [Sound](https://github.com/robertrypula/AudioNetwork)
* IR - some phones come with both transmitters and receivers for IR, and it's also possible to build hardware specifically for this purpose

_Again, apologies if this is out of scope, has already been discussed, or is being asked in the wrong place_

**Comment by samuk** [comment]
There's been some work on peer to peer messaging in other projects. Notably

http://www.servalproject.org/

https://briarproject.org/

**Comment by samuk** [comment]
Think this could be achieved by hosting https://manyver.se/ or other apps on the SD card, and serving the files over Wifi. 

Related to https://github.com/sudomesh/disaster-radio/issues/59
