### ISSUE TITLE
this is all hardware?

### ISSUE THREAD

**Issue by and09** [sudomesh/disaster-radio#12]
If I buy a powerbank and this
https://www.banggood.com/2Pcs-Wemos-TTGO-LORA-SX1278-ESP32-0_96-OLED-Module-16-Mt-Bytes-128-Mt-bit-433Mhz-For-Arduino-p-1270420.html?

This is all waht I need?
Is possible to connect esp to baofeng sound cable?

**Comment by philippeowagner** [comment]
I ordered [this one](https://de.aliexpress.com/item/868-mhz-915-mhz-LoRa-ESP32-Oled-Wifi-SX1276-Modul-IOT-mit-Antenne-F-r-Arduino/32836246848.html) a few days ago. It was suggested suggested [on the mailing list](https://sudoroom.org/pipermail/disasterradio/2017-December/000032.html).

**Comment by Juul** [comment]
We're porting the software to the ESP32 and the one Philippe linked is the
one I'm using for testing so it should work on it soon. Currently we're
still on the ESP8266 but we want to move to the ESP32 as soon as possible.

On Tue, Sep 4, 2018 at 1:28 PM, Philippe O. Wagner <notifications@github.com

**Comment by philippeowagner** [comment]
The e-mail was a bit older... Lucky me that the model is still compatible.

**Comment by samuk** [comment]
Grant has been making some progress with the code https://github.com/sudomesh/disaster-radio/pull/25#issuecomment-550434519

For these boards https://www.aliexpress.com/item/32915894264.html?spm=a2g0o.productlist.0.0.671054bdhI1Hix&algo_pvid=aec249fc-c80a-4c81-8220-334dc9f635b1&algo_expid=aec249fc-c80a-4c81-8220-334dc9f635b1-0&btsid=6d976d5a-e661-47f6-b371-7f0bc42c5336&ws_ab_test=searchweb0_0,searchweb201602_7,searchweb201603_55
