### ISSUE TITLE
MPPT solar charge controller module

### ISSUE THREAD

**Issue by Juul** [sudomesh/disaster-radio#31]
I've started a [wiki page](https://github.com/sudomesh/disaster-radio/wiki/Solar-MPPT-battery-charge-controller) on the MPPT solar charge controller we want to build.

For the next iteration of disaster.radio we're aiming to make this a separate module so it can be re-used for other projects.

More research is still needed to compare the different MPPT charge controller chips, figure out if better chips exist or if it makes more sense to make it entirely from scratch with a low-power microcontroller.

**Comment by samuk** [comment]
The link appears in wikipage list, so open ticket no longer needed.
