### ISSUE TITLE
868 Mhz setting for Europe

### ISSUE THREAD

**Issue by samuk** [sudomesh/disaster-radio#43]
What would be the best way to enable 868Mhz operation for Europe?

It looks like 915Mhz is set here: https://github.com/sudomesh/LoRaLayer2/blob/3b61485779c0cfdad58a785a3e5b912f0cec5b7b/src/Layer1_LoRa.cpp#L150

Related to this, how can you set the power? We are limited to 500mW from memory.

**Comment by paidforby** [comment]
The only way, right now, is to change that value on line 150 of Layer1_LoRa.cpp. I can easily expose that setting to main.ino, so it can be changed at that level.

This would be a good setting to expose to the web-gui/console configuration manager that I am working on also.

**Comment by samuk** [comment]
Thanks, will test soon!
