### ISSUE TITLE
Enable Build Without SD Card Support

### ISSUE THREAD

**Issue by candrist** [sudomesh/disaster-radio#47]
Can an option be made to work without SD Card Support?

I'm Using an ESP32

**Comment by paidforby** [comment]
Yes, this should be supported by default. main.ino contains the following lines,
```
    sdCardSetup();
    if(!sdInitialized){
        spiffsSetup();
    }    
```
If an SD card is available, it will attempt to use that as the file system. If not, it will fall back to using the SPIFFS (the on-board SPI flash file system). What type of ESP32 specifically are you using? And what development board is it on? There are lots of different models out there.

**Comment by candrist** [comment]
I am using the following board.

**Comment by candrist** [comment]
Thanks!
