### ISSUE TITLE
Setting broadcast power?

### ISSUE THREAD

**Issue by samuk** [sudomesh/disaster-radio#51]
Is there somewhere in the code that you can set broadcast power? In the UK/Europe we're limited to 500mW

https://www.ofcom.org.uk/__data/assets/pdf_file/0025/38095/final_report.pdf

**Comment by tlrobinson** [comment]
You can probably `#include <LoRa.h>` then use `LoRa.setTxPower(txPower);` (in dB) https://github.com/sandeepmistry/arduino-LoRa/blob/master/API.md#tx-power

It might be good to expose that (and other methods) in LoRaLayer2’s Layer1. I’ve filed an issue here https://github.com/sudomesh/LoRaLayer2/issues/6

**Comment by samuk** [comment]
https://github.com/sudomesh/LoRaLayer2/commit/87fa96224bfe904a94a5f9aa25081538343d5ed1
