### ISSUE TITLE
Hardware support for LILYGO TTGO ESP32-Paxcounter

### ISSUE THREAD

**Issue by lbrunkho** [sudomesh/disaster-radio#60]
Just wondering if there's any reason why this premade board wouldn't work.

Aliexpress US $18.31 | LILYGO® TTGO ESP32-Paxcounter LoRa32 V2.1 1.6 Version 433/868/915MHZ LoRa ESP-32 OLED 0.96 Inch SD Card Bluetooth WIFI Module
https://a.aliexpress.com/_d7ZjYQP

It seems to have all the modules needed for basic functionality and is would be very cost effective way to depoy a larger network. I am aware that the LoRa radio on this may not be powerful enough to achieve maximum distance.

**Comment by samuk** [comment]
Hi welcome,

That's the board we're mostly using at the moment. 

We've actually got Lilygo to flash it with the our firmware, you can buy the pre-flashed version here: https://www.aliexpress.com/item/4000396836096.html

More info on hardware can be found here: https://github.com/sudomesh/disaster-radio/wiki/Devices--&-Hardware
