### ISSUE TITLE
Rotate WeMos (or move SMA connector)

### ISSUE THREAD

**Issue by morganrallen** [sudomesh/disaster-radio#8]
Presently, mounting inside any sort of enclosure is impractical due to the SMA connector and USB port being pointed in the same direction. This might also warrant a higher level discussion around antenna connectors. Maybe using u.FL is more flexible when considering enclosures?

**Comment by samuk** [comment]
Is this resolved by plans for v5? https://github.com/sudomesh/disaster-radio/wiki/Board-v5-Plans

Can this ticket be closed?

**Comment by morganrallen** [comment]
It's for the original board, so I'm going to guess it can.
