### ISSUE TITLE
Youtube-error in introduction-video

### ISSUE THREAD

**Issue by johays** [sudomesh/disaster-radio#82]
When I try to view the intro-video on the webpage, I get the following youtube-error:

"_Video unavailable
This video contains content from KODA_CS. It is not available in your country._"

I come from a Danish IP. KODA is the main copyright-organisation in Denmark, but I do not see how your video violates any of their copyright-laws. (Had to go through a VPN to see the video).

Just wanted you to know, that some people might be unable to reach your content. Maybe talk to Youtube or use another video-provider.

**Comment by paidforby** [comment]
Thanks for pointing this out. fyi @jnny or @Juul, y'all might be the best folks to contact the youtubes.

**Comment by jnny** [comment]
Able to access via a Danish VPN server - there's a Content ID notice but not a copyright strike. Closing this.
